# Generated by Django 4.2.3 on 2023-07-05 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="photo",
            field=models.ImageField(
                blank=True, null=True, upload_to="diary-photo", verbose_name="이미지"
            ),
        ),
    ]
