# Generated by Django 4.2.3 on 2023-07-06 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0002_alter_post_photo"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="comment_count",
            field=models.IntegerField(default=0, verbose_name="댓글수"),
        ),
    ]
